# Generated by Django 6.0 on 2026-03-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicant_profile", "0007_usercontext_unique_context_per_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontext",
            name="context_hash",
            field=models.CharField(db_index=True, default="", max_length=64),
        ),
    ]
